name: Test

on:
  pull_request:
    branches: [master]

jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make CLI version
        run: make

      - name: Download latest GCLC release
        run: |
          mkdir latest
          cd latest
          wget https://github.com/janicicpredrag/gclc/releases/latest/download/linux.zip
          unzip linux.zip gclc
          chmod +x gclc

      - name: Run tests
        run: |
          ./test/compare_outputs.sh executable/gclc latest/gclc ./samples/basic_samples/
          ./test/compare_proofs.sh executable/gclc latest/gclc ./samples/samples_prover/

      - name: Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const fs = require("fs");

            function loadLog(filename) {
              try {
                return fs.readFileSync(filename, { encoding: "utf8", flag: "r" });
              } catch (error) {
                return `Error: Cant load ${filename}`;
              }
            }

            const outputLog = loadLog("diff-log");
            const proofLog = loadLog("proof-log");

            const body = `## Basic samples \n ${log} \n ## Prover samples \n ${proofLog}`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
